using System.Drawing.Drawing2D;
namespace SatisfactoryPlanner;
public class MapPosition {public float X {get;set;}public float Y {get;set;}}
internal sealed class MachineMap:Panel {
 internal sealed record Node(string Key,string Title,string Subtitle,string Detail,string Footer,bool Raw,bool Target);
 internal sealed record Edge(string From,string To,string Label);
 readonly List<Node> nodes=[];readonly List<Edge> edges=[];Settings? settings;GameData? data;Plan? plan;
 readonly Canvas canvas;readonly Label hint=Theme.Label("",9,false,Theme.Muted);float zoom=1;PointF pan=new(30,30);string? dragging;Point mouse;bool panning;string signature="";
 const int NodeWidth=265,NodeHeight=139;
 public MachineMap(){Dock=DockStyle.Fill;canvas=new Canvas(this){Dock=DockStyle.Fill};var layout=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=2,Margin=Padding.Empty};layout.RowStyles.Add(new(SizeType.Absolute,45));layout.RowStyles.Add(new(SizeType.Percent,100));Controls.Add(layout);var toolbar=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=false};layout.Controls.Add(toolbar,0,0);void Button(string title,Action action,int width){var b=new ModernButton{Text=title,Width=width,Height=33,Margin=new Padding(0,0,7,0)};b.Click+=(_,_)=>action();toolbar.Controls.Add(b);}Button("−",()=>Zoom(.8f,new Point(canvas.Width/2,canvas.Height/2)),36);Button("+",()=>Zoom(1.25f,new Point(canvas.Width/2,canvas.Height/2)),36);Button("Alles zeigen",Fit,112);Button("Neu anordnen",()=>{if(settings!=null){settings.MapPositions.Clear();AutoLayout();Fit();}},128);hint.Size=new Size(470,34);hint.TextAlign=ContentAlignment.MiddleLeft;toolbar.Controls.Add(hint);layout.Controls.Add(canvas,0,1);canvas.Resize+=(_,_)=>{if(!Visible)return;if(nodes.Count>0&&canvas.Width>0&&canvas.Height>0)Fit();};VisibleChanged+=(_,_)=>{if(Visible)Fit();};}
 static string Key(Stage s)=>s.Building.Id+"|"+(s.Recipe?.Id??s.Item);
 public void SetPlan(GameData data,Plan plan,Settings settings){this.data=data;this.plan=plan;this.settings=settings;nodes.Clear();edges.Clear();var stages=plan.Stages;
  foreach(var s in stages){nodes.Add(new Node(Key(s),s.Building.Name,data.Name(s.Item),$"{s.Count} × bei {s.Clock:0.##} % Takt",$"{s.Rate:0.###} {data.Unit(s.Item)} · {s.Power:0.##} MW",s.Recipe==null,s.Item==settings.Target));}
  foreach(var (id,amount) in plan.External)nodes.Add(new Node("external|"+id,"Extern bereitstellen",data.Name(id),"Benötigte Zufuhr pro Minute",$"{amount:0.###} {data.Unit(id)}",true,false));
  var supplies=new Dictionary<string,List<(string Key,double Amount)>>();void Supply(string item,string key,double amount){if(!supplies.ContainsKey(item))supplies[item]=[];supplies[item].Add((key,amount));}
  foreach(var s in stages){if(s.Recipe!=null){double runs=s.Rate/s.Recipe.Outputs[0].Amount;foreach(var q in s.Recipe.Outputs)Supply(q.Item,Key(s),q.Amount*runs);}else if(s.Building.Id!="Build_FrackingSmasher_C")Supply(s.Item,Key(s),s.Rate);}
  foreach(var (id,amount) in plan.External)Supply(id,"external|"+id,amount);
  foreach(var s in stages.Where(s=>s.Recipe!=null)){double runs=s.Rate/s.Recipe!.Outputs[0].Amount;foreach(var q in s.Recipe.Inputs){double need=q.Amount*runs;if(!supplies.TryGetValue(q.Item,out var list))continue;for(int i=0;i<list.Count&&need>1e-7;i++){var supply=list[i];double amount=Math.Min(need,supply.Amount);if(amount<1e-7)continue;edges.Add(new Edge(supply.Key,Key(s),data.Name(q.Item)+$" · {amount:0.###} {data.Unit(q.Item)}"));list[i]=(supply.Key,supply.Amount-amount);need-=amount;}}}
  foreach(var compressor in stages.Where(s=>s.Building.Id=="Build_FrackingSmasher_C")){var extractor=stages.FirstOrDefault(s=>s.Item==compressor.Item&&s.Building.Id=="Build_FrackingExtractor_C");if(extractor!=null)edges.Add(new Edge(Key(compressor),Key(extractor),"Versorgt die Rohstoffquelle"));}
  AutoLayout();var next=settings.Target+"|"+string.Join(";",nodes.Select(n=>n.Key));bool changed=signature!=next;signature=next;if(changed)Fit();UpdateHint();canvas.Invalidate();}
 public void Clear(){nodes.Clear();edges.Clear();canvas.Invalidate();}
 void AutoLayout(){if(settings==null)return;var levels=new Dictionary<string,int>();foreach(var n in nodes.Where(n=>n.Raw))levels[n.Key]=0;for(int iteration=0;iteration<nodes.Count;iteration++){bool change=false;foreach(var n in nodes.Where(n=>!levels.ContainsKey(n.Key))){var parents=edges.Where(e=>e.To==n.Key&&e.From!=n.Key).Select(e=>e.From).Distinct().ToList();if(parents.All(levels.ContainsKey)){levels[n.Key]=parents.Count==0?0:parents.Max(p=>levels[p])+1;change=true;}}if(!change)break;}int fallback=levels.Values.DefaultIfEmpty(0).Max()+1;foreach(var n in nodes)if(!levels.ContainsKey(n.Key))levels[n.Key]=fallback;var rows=new Dictionary<int,int>();foreach(var n in nodes){int level=levels[n.Key];int row=rows.GetValueOrDefault(level);rows[level]=row+1;if(!settings.MapPositions.TryGetValue(n.Key,out var pos)||!float.IsFinite(pos.X)||!float.IsFinite(pos.Y))settings.MapPositions[n.Key]=new(){X=level*350,Y=row*200};}}
 RectangleF GraphBounds(){if(settings==null||nodes.Count==0)return new(0,0,1,1);float x=nodes.Min(n=>settings.MapPositions[n.Key].X),y=nodes.Min(n=>settings.MapPositions[n.Key].Y),r=nodes.Max(n=>settings.MapPositions[n.Key].X+NodeWidth),b=nodes.Max(n=>settings.MapPositions[n.Key].Y+NodeHeight);return new(x,y,r-x,b-y);}
 internal void Fit(){if(canvas.Width<1||canvas.Height<1||nodes.Count==0)return;var b=GraphBounds();zoom=Math.Clamp(Math.Min((canvas.Width-70)/b.Width,(canvas.Height-70)/b.Height),.12f,1.2f);pan=new((canvas.Width-b.Width*zoom)/2-b.X*zoom,(canvas.Height-b.Height*zoom)/2-b.Y*zoom);UpdateHint();canvas.Invalidate();}
 void UpdateHint(){hint.Text=Ui.T($"{zoom*100:0} % · {nodes.Count} Maschinengruppen · Positionen im Plan gespeichert");hint.ForeColor=Theme.Muted;}
 PointF World(Point p)=>new((p.X-pan.X)/zoom,(p.Y-pan.Y)/zoom);
 void Zoom(float factor,Point anchor){var before=World(anchor);zoom=Math.Clamp(zoom*factor,.12f,3f);pan=new(anchor.X-before.X*zoom,anchor.Y-before.Y*zoom);UpdateHint();canvas.Invalidate();}
 string? Hit(Point point){if(settings==null)return null;var p=World(point);return nodes.LastOrDefault(n=>{var pos=settings.MapPositions[n.Key];return new RectangleF(pos.X,pos.Y,NodeWidth,NodeHeight).Contains(p);})?.Key;}
 void Down(MouseEventArgs e){canvas.Focus();mouse=e.Location;dragging=e.Button==MouseButtons.Left?Hit(e.Location):null;panning=dragging==null&&(e.Button==MouseButtons.Left||e.Button==MouseButtons.Middle||e.Button==MouseButtons.Right);canvas.Capture=dragging!=null||panning;canvas.Cursor=dragging!=null?Cursors.SizeAll:panning?Cursors.Hand:Cursors.Default;}
 void DragMove(MouseEventArgs e){if(settings==null)return;float dx=e.X-mouse.X,dy=e.Y-mouse.Y;if(dragging!=null){var pos=settings.MapPositions[dragging];pos.X+=dx/zoom;pos.Y+=dy/zoom;}else if(panning)pan=new(pan.X+dx,pan.Y+dy);mouse=e.Location;if(dragging!=null||panning)canvas.Invalidate();else canvas.Cursor=Hit(e.Location)!=null?Cursors.SizeAll:Cursors.Default;}
 void Up(){dragging=null;panning=false;canvas.Capture=false;canvas.Cursor=Cursors.Default;}
 void Draw(Graphics g){g.Clear(Theme.Canvas);g.SmoothingMode=SmoothingMode.AntiAlias;using(var dot=new SolidBrush(Theme.Line)){float spacing=30*zoom;if(spacing>=12)for(float x=(pan.X%spacing+spacing)%spacing;x<canvas.Width;x+=spacing)for(float y=(pan.Y%spacing+spacing)%spacing;y<canvas.Height;y+=spacing)g.FillEllipse(dot,x,y,2,2);}
  if(settings==null||nodes.Count==0){TextRenderer.DrawText(g,Ui.T("Berechne ein Produkt, um deinen Bauplan zu sehen."),Font,canvas.ClientRectangle,Theme.Muted,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter);return;}
  g.TranslateTransform(pan.X,pan.Y);g.ScaleTransform(zoom,zoom);
  foreach(var e in edges){var from=settings.MapPositions[e.From];var to=settings.MapPositions[e.To];PointF a=new(from.X+NodeWidth,from.Y+NodeHeight/2),b=new(to.X,to.Y+NodeHeight/2);using var path=new GraphicsPath();float bend=Math.Max(70,Math.Abs(b.X-a.X)*.5f);path.AddBezier(a,new PointF(a.X+bend,a.Y),new PointF(b.X-bend,b.Y),b);using var pen=new Pen(Theme.Dark?Color.FromArgb(101,134,179):Color.FromArgb(126,150,183),2.2f){CustomEndCap=new AdjustableArrowCap(4,5)};g.DrawPath(pen,path);if(zoom>=.48f){using var font=new Font("Segoe UI",8);var size=g.MeasureString(Ui.T(e.Label),font);float x=(a.X+b.X-size.Width)/2,y=(a.Y+b.Y)/2-19;using var background=new SolidBrush(Theme.Canvas);g.FillRectangle(background,x-4,y-2,size.Width+8,size.Height+4);using var ink=new SolidBrush(Theme.Muted);g.DrawString(Ui.T(e.Label),font,ink,x,y);}}
  foreach(var n in nodes){var pos=settings.MapPositions[n.Key];var r=new Rectangle((int)pos.X,(int)pos.Y,NodeWidth,NodeHeight);using var path=Theme.Round(r,12);using var surface=new SolidBrush(Theme.Surface);g.FillPath(surface,path);var accent=n.Target?Theme.Orange:n.Raw?Color.FromArgb(43,169,148):Color.FromArgb(79,134,215);using var border=new Pen(n.Key==dragging?accent:Theme.Line,n.Key==dragging?2:1);g.DrawPath(border,path);using var stripe=new SolidBrush(accent);g.FillRectangle(stripe,pos.X+15,pos.Y+16,4,23);
   void Text(string text,float size,bool bold,Color color,int y,int height){using var font=new Font("Segoe UI",size,bold?FontStyle.Bold:FontStyle.Regular);using var brush=new SolidBrush(color);using var format=new StringFormat{Trimming=StringTrimming.EllipsisCharacter,FormatFlags=StringFormatFlags.NoWrap};g.DrawString(Ui.T(text),font,brush,new RectangleF(pos.X+27,pos.Y+y,NodeWidth-40,height),format);}
   Text(n.Title,12,true,Theme.Ink,16,25);Text(n.Subtitle,10,false,Theme.Muted,46,24);Text(n.Detail,11,true,accent,76,23);Text(n.Footer,9,false,Theme.Muted,107,22);
  }
 }
 internal void TestInteraction(){if(settings==null||nodes.Count==0)throw new Exception("Map is empty.");Fit();var pos=settings.MapPositions[nodes[0].Key];float oldX=pos.X;var click=new Point((int)(pan.X+(pos.X+40)*zoom),(int)(pan.Y+(pos.Y+40)*zoom));Down(new MouseEventArgs(MouseButtons.Left,1,click.X,click.Y,0));DragMove(new MouseEventArgs(MouseButtons.Left,0,click.X+50,click.Y+25,0));Up();if(pos.X<=oldX)throw new Exception("Machine drag failed.");var before=pan;Down(new MouseEventArgs(MouseButtons.Middle,1,5,5,0));DragMove(new MouseEventArgs(MouseButtons.Middle,0,35,45,0));Up();if(pan==before)throw new Exception("Map pan failed.");float oldZoom=zoom;Zoom(1.2f,new Point(100,100));if(zoom<=oldZoom)throw new Exception("Map zoom failed.");var restored=System.Text.Json.JsonSerializer.Deserialize<Settings>(System.Text.Json.JsonSerializer.Serialize(settings))!;if(restored.MapPositions[nodes[0].Key].X!=pos.X)throw new Exception("Map position persistence failed.");}
 sealed class Canvas(MachineMap owner):Control {

  protected override void OnPaint(PaintEventArgs e)=>owner.Draw(e.Graphics);
  protected override void OnMouseDown(MouseEventArgs e){base.OnMouseDown(e);owner.Down(e);}
  protected override void OnMouseMove(MouseEventArgs e){base.OnMouseMove(e);owner.DragMove(e);}
  protected override void OnMouseUp(MouseEventArgs e){base.OnMouseUp(e);owner.Up();}
  protected override void OnMouseWheel(MouseEventArgs e){base.OnMouseWheel(e);owner.Zoom(e.Delta>0?1.15f:1/1.15f,e.Location);}
  protected override void OnHandleCreated(EventArgs e){base.OnHandleCreated(e);SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer|ControlStyles.Selectable,true);}
 }
}




