using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Drawing.Drawing2D;

namespace SatisfactoryPlanner;
static class Program {
 [STAThread] static void Main(string[] args){
  ApplicationConfiguration.Initialize();
  try {var data=GameData.Load();if(args.Contains("--selftest")){Tests.Run(data);SurplusGuidance.Test(data);return;}if(args.Contains("--settings-test")){MainForm.AppearanceFileOverride=args[Array.IndexOf(args,"--settings-test")+1];using var testForm=new MainForm(data);testForm.TestSettingsMenu();return;}if(args.Contains("--ui-test")){MainForm.AppearanceFileOverride=args[Array.IndexOf(args,"--ui-test")+1];using var testForm=new MainForm(data);testForm.TestAppearance();return;}var form=new MainForm(data);if(args.Contains("--material-test")){form.TestMaterials();return;}if(args.Contains("--map-test")){form.TestMap();return;}if(args.Contains("--window-test")){form.TestWindowRestore();return;}if(args.Any(a=>a.StartsWith("--screenshot"))){if(args.Contains("--screenshot-small")){form.Width=1180;form.Height=800;}form.Show();Application.DoEvents();if(args.Contains("--screenshot-en"))form.SetLanguage("en");if(args.Contains("--screenshot-dark"))form.SetDark(true,false);if(args.Contains("--screenshot-light"))form.SetDark(false,false);if(args.Contains("--screenshot-surplus"))form.PreviewSurplus();if(args.Contains("--screenshot-materials"))form.PreviewPage("Baukosten");if(args.Contains("--screenshot-recipes"))form.PreviewPage("Rezepte");if(args.Contains("--screenshot-map"))form.PreviewPage("Karte");if(args.Contains("--screenshot-machines"))form.PreviewPage("Maschinen");if(args.Contains("--screenshot-advanced"))form.PreviewPage("+  Rohstoff-Einstellungen");if(args.Contains("--screenshot-settings"))form.PreviewSettings();Application.DoEvents();using var bitmap=new Bitmap(form.Width,form.Height);form.DrawToBitmap(bitmap,new Rectangle(0,0,form.Width,form.Height));bitmap.Save(Path.Combine(AppContext.BaseDirectory,"Vorschau.png"));form.Close();return;}Application.Run(form);}
  catch(Exception ex){if(args.Contains("--selftest")||args.Contains("--ui-test")||args.Contains("--window-test")||args.Contains("--map-test")||args.Contains("--material-test")||args.Contains("--settings-test"))throw;MessageBox.Show(ex.Message,"Satisfactory Planer",MessageBoxButtons.OK,MessageBoxIcon.Error);}
 }
}
public partial class MainForm:Form {
 readonly GameData data;readonly Engine engine; Settings settings=new();Plan? plan;bool initializing=true;
 readonly ComboBox target=new(){DropDownStyle=ComboBoxStyle.DropDownList,Width=300};
 readonly TextBox search=new(){Width=300,PlaceholderText="Produkt suchen …"};
 readonly NumericUpDown rate=new(){Minimum=.001m,Maximum=10000000,DecimalPlaces=3,Value=5,Width=120,ThousandsSeparator=true};
 readonly CheckBox overclock=new(){Text="Übertakten erlauben",AutoSize=true};
 readonly NumericUpDown clock=new(){Minimum=100,Maximum=250,Value=250,Width=80,Increment=25,Enabled=false};
 readonly ComboBox miner=new(){DropDownStyle=ComboBoxStyle.DropDownList,Width=115};
 readonly ComboBox purity=new(){DropDownStyle=ComboBoxStyle.DropDownList,Width=130};
 readonly NumericUpDown nodes=new(){Minimum=1,Maximum=20,Value=6,Width=55};
 readonly Label summary=new(){AutoSize=false,Dock=DockStyle.Fill,Font=new Font("Segoe UI",17,FontStyle.Bold),ForeColor=Color.FromArgb(255,170,70),Padding=new Padding(16,12,8,0)};
 readonly Label status=new(){Dock=DockStyle.Fill,Padding=new Padding(16,8,16,4),ForeColor=Color.FromArgb(184,195,210)};

 readonly MachineMap machineMap=new();
 readonly Panel overview=new(){Dock=DockStyle.Fill,AutoScroll=true,BackColor=Theme.Canvas};
 readonly Label machineValue=Theme.Label("—"),machineHint=Theme.Label(""),powerValue=Theme.Label("—"),powerHint=Theme.Label(""),rawValue=Theme.Label("—"),rawHint=Theme.Label(""),surplusValue=Theme.Label("—"),surplusHint=Theme.Label("");
 readonly DataGridView stages=Grid(),resources=Grid(),surplus=Grid(),costs=Grid(),recipes=Grid();
 readonly TreeView tree=new(){Dock=DockStyle.Fill,BackColor=Color.FromArgb(26,33,44),ForeColor=Color.White,BorderStyle=BorderStyle.None,Font=new Font("Segoe UI",11),ItemHeight=29};
 readonly TextBox notes=new(){Multiline=true,ReadOnly=true,Dock=DockStyle.Fill,ScrollBars=ScrollBars.Vertical,BackColor=Color.FromArgb(26,33,44),ForeColor=Color.FromArgb(220,225,234),BorderStyle=BorderStyle.None,Font=new Font("Segoe UI",11)};
 static DataGridView Grid()=>new(){Dock=DockStyle.Fill,BackgroundColor=Color.White,BorderStyle=BorderStyle.None,AllowUserToAddRows=false,AllowUserToDeleteRows=false,RowHeadersVisible=false,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill,ReadOnly=true,SelectionMode=DataGridViewSelectionMode.FullRowSelect,MultiSelect=false,EnableHeadersVisualStyles=false,RowTemplate={Height=43},ColumnHeadersHeight=45,CellBorderStyle=DataGridViewCellBorderStyle.SingleHorizontal,ColumnHeadersBorderStyle=DataGridViewHeaderBorderStyle.None,ColumnHeadersDefaultCellStyle=new(){BackColor=Color.FromArgb(236,241,248),ForeColor=Theme.Muted,Font=new Font("Segoe UI",9,FontStyle.Bold),Padding=new Padding(8,0,8,0)},DefaultCellStyle=new(){BackColor=Color.White,ForeColor=Theme.Ink,SelectionBackColor=Color.FromArgb(234,242,254),SelectionForeColor=Theme.Ink,Font=new Font("Segoe UI",10),Padding=new Padding(8,0,8,0)},AlternatingRowsDefaultCellStyle=new(){BackColor=Color.FromArgb(250,252,255)},GridColor=Theme.Line};
 static void Columns(DataGridView g,params string[] cols){foreach(var c in cols)g.Columns.Add(c,c);}
 static string N(double x)=>x.ToString("N3",Ui.Culture).TrimEnd('0').TrimEnd(Ui.Culture.NumberFormat.NumberDecimalSeparator[0]);
 public MainForm(GameData data){
  var iconAssembly=typeof(MainForm).Assembly;
  using(var iconStream=iconAssembly.GetManifestResourceStream(iconAssembly.GetManifestResourceNames().Single(n=>n.EndsWith(".AppIcon.ico")))){Icon=new Icon(iconStream!);}
  this.data=data;engine=new(data);Text="Satisfactory · Fabrikplaner";Width=1440;Height=940;MinimumSize=new Size(1180,800);StartPosition=FormStartPosition.CenterScreen;BackColor=Theme.Canvas;ForeColor=Theme.Ink;Font=new Font("Segoe UI",10);DoubleBuffered=true;
  var shell=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=1,Margin=Padding.Empty};shell.ColumnStyles.Add(new(SizeType.Absolute,330));shell.ColumnStyles.Add(new(SizeType.Percent,100));Controls.Add(shell);
  var sidebar=new Panel{Tag="sidebar",Dock=DockStyle.Fill,BackColor=Color.FromArgb(23,34,52),Margin=Padding.Empty,Padding=new Padding(20)};shell.Controls.Add(sidebar,0,0);
  var sideScroll=new Panel{Dock=DockStyle.Fill,AutoScroll=true};sidebar.Controls.Add(sideScroll);
  var side=new FlowLayoutPanel{FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoSize=true,Width=265,Location=new Point(0,0)};sideScroll.Controls.Add(side);
  Label SideLabel(string text,int height=25,float size=10,bool bold=false){var l=Theme.Label(text,size,bold,Color.FromArgb(219,228,241));l.Width=258;l.Height=height;l.Margin=new Padding(0,4,0,4);side.Controls.Add(l);return l;}
  SideLabel("F  /  FACTORY",25,12,true).ForeColor=Theme.Orange;SideLabel("Satisfactory Planer",37,17,true);SideLabel("Vom Wunschprodukt zum Bauplan.",47,10).ForeColor=Color.FromArgb(156,174,196);
  SideLabel("01   WAS MÖCHTEST DU HERSTELLEN?",34,9,true);
  search.Width=258;search.Height=34;search.Font=new Font("Segoe UI",11);search.Margin=new Padding(0,0,0,10);search.PlaceholderText="Zum Beispiel: Eisenplatte";side.Controls.Add(search);
  target.Width=258;target.Font=new Font("Segoe UI",11);target.Margin=new Padding(0,0,0,6);side.Controls.Add(target);SideLabel("Suche einen Namen und wähle dein Produkt.",43,9).ForeColor=Color.FromArgb(156,174,196);
  SideLabel("02   WIE VIEL PRO MINUTE?",30,9,true);rate.Width=258;rate.Font=new Font("Segoe UI",16);rate.DecimalPlaces=3;rate.Margin=new Padding(0,0,0,6);side.Controls.Add(rate);
  SideLabel("5 bedeutet: Deine Fabrik liefert jede Minute\n5 Stück. Flüssigkeiten werden in m³ gerechnet.",52,9).ForeColor=Color.FromArgb(156,174,196);
  SideLabel("03   WIE SOLLEN DIE MASCHINEN LAUFEN?",34,9,true);
  overclock.ForeColor=Color.White;overclock.Text="Weniger Maschinen durch Übertakten";overclock.Font=new Font("Segoe UI",9);overclock.Margin=new Padding(0,3,0,4);side.Controls.Add(overclock);
  SideLabel("Schnellere Maschinen brauchen mehr Strom\nund Leistungssplitter.",44,9).ForeColor=Color.FromArgb(156,174,196);
  var clockLine=new FlowLayoutPanel{Width=258,Height=40,Margin=Padding.Empty};var maxLabel=Theme.Label("Maximaler Takt",10,false,Color.White);maxLabel.Size=new Size(160,30);maxLabel.TextAlign=ContentAlignment.MiddleLeft;clockLine.Controls.Add(maxLabel);clock.Width=85;clock.Font=new Font("Segoe UI",11);clockLine.Controls.Add(clock);side.Controls.Add(clockLine);
  var calculate=new ModernButton{Text="Bauplan berechnen  →",Primary=true,Width=258,Height=45,Margin=new Padding(0,12,0,14)};calculate.Click+=(_,_)=>Calculate();side.Controls.Add(calculate);
  var advancedButton=new ModernButton{Text="+  Rohstoff-Einstellungen",Sidebar=true,Width=258,Margin=new Padding(0,0,0,8)};side.Controls.Add(advancedButton);
  var advanced=new FlowLayoutPanel{FlowDirection=FlowDirection.TopDown,WrapContents=false,Width=258,Height=285,Visible=false,Margin=Padding.Empty};side.Controls.Add(advanced);
  void Advanced(string title,Control control,string hint){var label=Theme.Label(title,10,true,Color.White);label.Size=new Size(250,24);advanced.Controls.Add(label);control.Width=250;advanced.Controls.Add(control);var help=Theme.Label(hint,9,false,Color.FromArgb(156,174,196));help.Size=new Size(250,39);advanced.Controls.Add(help);}
  miner.Items.AddRange(["Miner Mk.1","Miner Mk.2","Miner Mk.3"]);miner.SelectedIndex=0;purity.Items.AddRange(["Unrein · halber Ertrag","Normal · einfacher Ertrag","Rein · doppelter Ertrag"]);purity.SelectedIndex=1;
  Advanced("Deine Miner-Stufe",miner,"Mk.1 ist die erste Fördermaschine im Spiel.");Advanced("Reinheit deiner Vorkommen",purity,"Steht am Vorkommen. Gilt hier für alle Erze, Öl und Stickstoff.");Advanced("Stickstoff: Unterknoten pro Quelle",nodes,"Nur für Produkte relevant, die Stickstoff benötigen.");
  advancedButton.Click+=(_,_)=>{advanced.Visible=!advanced.Visible;advancedButton.Text=Ui.T(advanced.Visible?"−  Rohstoff-Einstellungen":"+  Rohstoff-Einstellungen");};
  var settingsButton=new ModernButton{Text="Einstellungen",Sidebar=true,Width=258,Margin=new Padding(0,0,0,8)};settingsButton.Click+=(_,_)=>OpenSettings();side.Controls.Add(settingsButton);
  SideLabel("OFFLINE BEREIT\nRezepte aus deiner Spielinstallation.",55,9).ForeColor=Color.FromArgb(133,158,187);
  var main=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=6,Padding=new Padding(24,12,24,12),Margin=Padding.Empty};main.RowStyles.Add(new(SizeType.Absolute,73));main.RowStyles.Add(new(SizeType.Absolute,65));main.RowStyles.Add(new(SizeType.Absolute,112));main.RowStyles.Add(new(SizeType.Absolute,57));main.RowStyles.Add(new(SizeType.Percent,100));main.RowStyles.Add(new(SizeType.Absolute,40));shell.Controls.Add(main,1,0);
  var top=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=1};top.ColumnStyles.Add(new(SizeType.Percent,100));top.ColumnStyles.Add(new(SizeType.Absolute,377));main.Controls.Add(top,0,0);
  var titlePanel=new Panel{Dock=DockStyle.Fill};var title=Theme.Label("Deine Fabrik. Dein Plan.",23,true);title.Dock=DockStyle.Top;title.Height=39;titlePanel.Controls.Add(title);var subtitle=Theme.Label("Produkt wählen. Menge festlegen. Mit dem Bauen beginnen.",10,false,Theme.Muted);subtitle.Dock=DockStyle.Bottom;subtitle.Height=25;titlePanel.Controls.Add(subtitle);top.Controls.Add(titlePanel,0,0);
  var actions=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(0,10,0,0),WrapContents=false};top.Controls.Add(actions,1,0);void ActionButton(string text,Action action,int width){var b=new ModernButton{Text=text,Width=width,Margin=new Padding(6,0,0,0)};b.Click+=(_,_)=>action();actions.Controls.Add(b);}ActionButton("Exportieren",Export,115);ActionButton("Öffnen",LoadPlan,90);ActionButton("Speichern",Save,110);
  summary.Font=new Font("Segoe UI",15,FontStyle.Bold);summary.ForeColor=Theme.Ink;summary.Padding=new Padding(0,14,0,0);summary.AutoEllipsis=true;main.Controls.Add(summary,0,1);
  var stats=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=4,RowCount=1,Margin=Padding.Empty};for(int i=0;i<4;i++)stats.ColumnStyles.Add(new(SizeType.Percent,25));main.Controls.Add(stats,0,2);
  void Metric(int col,string title,Label value,Label hint){var card=new Card{Dock=DockStyle.Fill,Margin=new Padding(col==0?0:6,0,col==3?0:6,5)};var label=Theme.Label(title,9,true,Theme.Muted);label.Location=new Point(17,12);label.Size=new Size(230,20);card.Controls.Add(label);value.Font=new Font("Segoe UI",23,FontStyle.Bold);value.ForeColor=col==0?Theme.Orange:Theme.Ink;value.Location=new Point(16,33);value.Size=new Size(230,36);value.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;card.Controls.Add(value);hint.Font=new Font("Segoe UI",9);hint.ForeColor=Theme.Muted;hint.Location=new Point(17,73);hint.Size=new Size(230,32);hint.AutoEllipsis=false;hint.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;card.Controls.Add(hint);stats.Controls.Add(card,col,0);EventHandler fit=(_,_)=>{label.Width=card.Width-34;value.Width=card.Width-32;hint.Width=card.Width-34;float size=23;using var graphics=card.CreateGraphics();while(size>12){using var font=new Font("Segoe UI",size,FontStyle.Bold);if(TextRenderer.MeasureText(value.Text,font).Width+8<=value.Width)break;size-=1;}value.Font=new Font("Segoe UI",size,FontStyle.Bold);};card.Resize+=fit;value.TextChanged+=fit;fit(card,EventArgs.Empty);}
  Metric(0,"MASCHINEN",machineValue,machineHint);Metric(1,"STROMBEDARF",powerValue,powerHint);Metric(2,"ROHSTOFFE",rawValue,rawHint);Metric(3,"ÜBERSCHÜSSE",surplusValue,surplusHint);
  var nav=new FlowLayoutPanel{Name="result-navigation",Dock=DockStyle.Fill,WrapContents=false,Padding=new Padding(0,8,0,0)};main.Controls.Add(nav,0,3);var pages=new Panel{Dock=DockStyle.Fill};main.Controls.Add(pages,0,4);var navButtons=new List<ModernButton>();var preferredWidths=new List<int>();
  void Page(string name,string explanation,Control content,int width){var page=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=2,Visible=false,Margin=Padding.Empty};page.RowStyles.Add(new(SizeType.Absolute,48));page.RowStyles.Add(new(SizeType.Percent,100));var help=Theme.Label(explanation,10,false,Theme.Muted);help.Dock=DockStyle.Fill;help.Padding=new Padding(0,7,0,0);page.Controls.Add(help,0,0);page.Controls.Add(content,0,1);pages.Controls.Add(page);var button=new ModernButton{Text=name,Width=width,Margin=new Padding(0,0,5,0)};nav.Controls.Add(button);navButtons.Add(button);preferredWidths.Add(width);button.Click+=(_,_)=>{foreach(Control p in pages.Controls)p.Visible=false;foreach(var b in navButtons){b.Selected=false;b.Invalidate();}page.Visible=true;page.BringToFront();button.Selected=true;button.Invalidate();};if(navButtons.Count==1){page.Visible=true;button.Selected=true;}}
  Page("Überblick","Dein Startpunkt: Diese Maschinen und Rohstoffe brauchst du für dein Ziel.",overview,95);
  Page("Maschinen","Jede Zeile ist eine Produktionsstufe. Baue die angegebene Anzahl und stelle den Takt ein.",stages,101);
  Page("Karte","Ziehen: Maschine anordnen · Freie Fläche ziehen: Karte verschieben · Mausrad: zoomen · Karten zeigen Maschinengruppen.",machineMap,75);
  Page("Kette","Klappe ein Produkt auf, um seine Zutaten zu sehen. Gemeinsame Zutaten sind in der Maschinenliste zusammengefasst.",tree,70);
  Page("Rohstoffe","Das verbraucht deine gesamte Fabrik jede Minute. Diese Mengen müssen dauerhaft ankommen.",resources,96);
  Page("Nebenprodukte","Vorschläge zum Abführen deiner Überschüsse. Zusätzliche Maschinen und Strom sind nicht eingerechnet; ein AWESOME-Schredder braucht 30 MW.",surplus,123);
  Page("Baukosten","Hake ab, welche Baumaterialien du vollständig hast. „Noch besorgen“ zeigt den Rest. Die Produktion bleibt unverändert.",costs,102);
  Page("Rezepte","Optional: Wähle andere Rezepte. Alternativrezepte musst du im Spiel zuerst freischalten.",recipes,86);
  Page("Hilfe","So funktioniert die Berechnung – und welche Annahmen in deinem Plan stecken.",notes,65);
  void ResizeNavigation(){if(WindowState==FormWindowState.Minimized)return;int available=nav.ClientSize.Width-nav.Padding.Horizontal-navButtons.Sum(b=>b.Margin.Horizontal);if(available<=0)return;double scale=Math.Min(1,(double)available/preferredWidths.Sum());nav.SuspendLayout();for(int i=0;i<navButtons.Count;i++){int width=Math.Max(1,(int)Math.Floor(preferredWidths[i]*scale));if(navButtons[i].Width!=width)navButtons[i].Width=width;}nav.ResumeLayout();}nav.Resize+=(_,_)=>ResizeNavigation();Resize+=(_,_)=>ResizeNavigation();Shown+=(_,_)=>ResizeNavigation();
  tree.BackColor=Color.White;tree.ForeColor=Theme.Ink;tree.FullRowSelect=true;tree.ShowLines=false;tree.Indent=25;tree.ItemHeight=33;notes.BackColor=Color.White;notes.ForeColor=Theme.Ink;
  Columns(stages,"Produkt","Rezept","Maschine","Anzahl","Takt pro Maschine","Ausgabe / min","Strom Ø · MW","Spitze · MW");stages.Columns[3].FillWeight=55;stages.Columns[3].MinimumWidth=70;stages.Columns[3].DefaultCellStyle.Font=new Font("Segoe UI",11,FontStyle.Bold);foreach(int index in new[]{3,4,5,6,7})stages.Columns[index].DefaultCellStyle.Alignment=DataGridViewContentAlignment.MiddleRight;
  Columns(resources,"Material","Pro Minute","Einheit","Bereitstellung");Columns(surplus,"Übriges Material","Pro Minute","Einheit","Entsorgung / Weiterverarbeitung");surplus.Columns[0].FillWeight=110;surplus.Columns[1].FillWeight=55;surplus.Columns[2].FillWeight=55;surplus.Columns[3].FillWeight=360;surplus.Columns[3].DefaultCellStyle.WrapMode=DataGridViewTriState.True;surplus.AutoSizeRowsMode=DataGridViewAutoSizeRowsMode.AllCells;surplus.DefaultCellStyle.Padding=new Padding(9,10,9,10);Columns(costs,"Baumaterial","Benötigte Stückzahl");
  recipes.ReadOnly=false;recipes.SelectionMode=DataGridViewSelectionMode.CellSelect;recipes.Columns.Add(new DataGridViewTextBoxColumn{Name="Produkt",HeaderText="Produkt",ReadOnly=true});recipes.Columns.Add(new DataGridViewComboBoxColumn{Name="Rezept",HeaderText="Gewähltes Rezept",DisplayStyle=DataGridViewComboBoxDisplayStyle.DropDownButton,FlatStyle=FlatStyle.Flat});recipes.CurrentCellDirtyStateChanged+=(_,_)=>{if(recipes.IsCurrentCellDirty)recipes.CommitEdit(DataGridViewDataErrorContexts.Commit);};recipes.CellValueChanged+=(_,e)=>{if(initializing||e.RowIndex<0||e.ColumnIndex!=1)return;var row=recipes.Rows[e.RowIndex];if(row.Tag is string id&&row.Cells[1].Value is string recipeId)settings.Choices[id]=recipeId;Calculate();};recipes.DataError+=(_,e)=>e.ThrowException=false;
  costs.ReadOnly=false;foreach(DataGridViewColumn col in costs.Columns)col.ReadOnly=true;costs.Columns.Add(new DataGridViewCheckBoxColumn{Name="Vorhanden",HeaderText="Schon vorhanden",ReadOnly=false});costs.Columns.Add(new DataGridViewTextBoxColumn{Name="Fehlt",HeaderText="Noch besorgen (Stück)",ReadOnly=true});costs.SelectionMode=DataGridViewSelectionMode.CellSelect;
  costs.CurrentCellDirtyStateChanged+=(_,_)=>{if(costs.IsCurrentCellDirty)costs.CommitEdit(DataGridViewDataErrorContexts.Commit);};costs.CellValueChanged+=(_,e)=>{if(initializing||e.RowIndex<0||e.ColumnIndex!=2||plan==null)return;var row=costs.Rows[e.RowIndex];if(row.Tag is not string id)return;bool owned=row.Cells[2].Value is true;if(owned)settings.OwnedMaterials.Add(id);else settings.OwnedMaterials.Remove(id);row.Cells[3].Value=owned?"0":N(plan.Costs[id]);};
  status.ForeColor=Theme.Muted;status.Font=new Font("Segoe UI",9);status.Padding=new Padding(0,11,0,0);main.Controls.Add(status,0,5);
  tips.SetToolTip(overclock,"Die App verteilt die Produktion auf weniger Maschinen. Dafür brauchst du mehr Strom und Leistungssplitter.");tips.SetToolTip(clock,"Obergrenze: 250 % bedeutet bis zu 2,5-mal so schnell wie normal. Der tatsächliche Takt wird passend zur Zielmenge berechnet.");tips.SetToolTip(rate,"Gewünschte Produktion pro Minute. Zum Beispiel 5 für fünf Stück in jeder Minute.");tips.SetToolTip(miner,"Wähle die Fördermaschine, die du im Spiel bauen kannst.");tips.SetToolTip(purity,"Die Reinheit steht am Rohstoffvorkommen. Ein reines Vorkommen liefert doppelt so viel wie ein normales.");
  Filter();target.SelectedValue=settings.Target;search.TextChanged+=(_,_)=>Filter();target.SelectedIndexChanged+=(_,_)=>{if(!initializing)Calculate();};rate.ValueChanged+=(_,_)=>{if(!initializing)Calculate();};overclock.CheckedChanged+=(_,_)=>{clock.Enabled=overclock.Checked;if(!initializing)Calculate();};clock.ValueChanged+=(_,_)=>{if(!initializing)Calculate();};miner.SelectedIndexChanged+=(_,_)=>{if(!initializing)Calculate();};purity.SelectedIndexChanged+=(_,_)=>{if(!initializing)Calculate();};nodes.ValueChanged+=(_,_)=>{if(!initializing)Calculate();};initializing=false;Calculate();InitializeAppearance();
 }

 void Filter(){bool old=initializing;initializing=true;var current=target.SelectedValue as string??settings.Target;var list=data.Items.Values.Where(i=>data.Options(i.Id).Count>0&&i.Name.Contains(search.Text,StringComparison.CurrentCultureIgnoreCase)).OrderBy(i=>i.Name).ToList();target.DisplayMember="Name";target.ValueMember="Id";target.DataSource=list;if(list.Any(i=>i.Id==current))target.SelectedValue=current;initializing=old;if(!old)Calculate();}
 void Read(){if(target.SelectedValue is not string id)throw new InvalidOperationException("Bitte ein Produkt auswählen.");settings.Target=id;settings.Rate=(double)rate.Value;settings.Overclock=overclock.Checked;settings.Clock=(double)clock.Value;settings.Miner=miner.SelectedIndex+1;settings.Purity=new[]{.5,1d,2d}[purity.SelectedIndex];settings.WellNodes=(int)nodes.Value;}
 void Calculate(){
  if(initializing)return;
  try {Read();plan=engine.Calculate(settings);summary.Text=$"Dein Ziel: {N(settings.Rate)} {data.Unit(settings.Target)} {data.Name(settings.Target)}";UpdateOverview();machineMap.SetPlan(data,plan,settings);
   stages.Rows.Clear();foreach(var s in plan.Stages.OrderBy(s=>s.Recipe is null).ThenBy(s=>data.Name(s.Item)))stages.Rows.Add(data.Name(s.Item),s.Recipe?.Name??"Rohstoffgewinnung",s.Building.Name,s.Count,N(s.Clock)+" %",N(s.Rate)+" "+data.Unit(s.Item),N(s.Power),N(s.Peak));
   resources.Rows.Clear();foreach(var (id,v) in plan.Raw.OrderBy(x=>data.Name(x.Key)))resources.Rows.Add(data.Name(id),N(v),data.Unit(id),"Förderanlagen enthalten");foreach(var (id,v) in plan.External.OrderBy(x=>data.Name(x.Key)))resources.Rows.Add(data.Name(id),N(v),data.Unit(id),"Extern bereitstellen");
   surplus.Rows.Clear();foreach(var (id,v) in plan.Surplus.OrderBy(x=>data.Name(x.Key)))surplus.Rows.Add(data.Name(id),N(v),data.Unit(id),SurplusGuidance.Advice(data,id,v));if(plan.Surplus.Count==0)surplus.Rows.Add("Keine Überschüsse", "0", "",Ui.T("Alles wird in deiner Produktionskette verwendet. Keine Entsorgung nötig."));
   costs.Rows.Clear();foreach(var (id,v) in plan.Costs.OrderBy(x=>data.Name(x.Key))){bool owned=settings.OwnedMaterials.Contains(id);int index=costs.Rows.Add(data.Name(id),N(v),owned,owned?"0":N(v));costs.Rows[index].Tag=id;}
   notes.Text=$"DATENQUELLE\r\n{data.Source}\r\nSteam-Build: {data.Build}\r\n{data.Recipes.Count} Maschinenrezepte; Namen aus den Sprachdateien deiner Installation.\r\n\r\nBERECHNUNG\r\nGanze Maschinen, gleichmäßig auf den erforderlichen Takt eingestellt. Der eingestellte Maximalwert begrenzt den Takt. Rohstoffbedarf verändert sich durch Übertaktung nicht.\r\nStrom: Basisleistung × Takt^{1.321929}; variable Maschinenleistung wird als Mittelwert und Spitze ausgewiesen.\r\n\r\n"+string.Join("\r\n\r\n",plan.Notes);
   initializing=true;recipes.Rows.Clear();var recipeItems=plan.Stages.Where(s=>s.Recipe!=null).Select(s=>s.Item).Append(settings.Target).Distinct().OrderBy(data.Name);foreach(var id in recipeItems){var options=data.Options(id);if(options.Count==0)continue;int index=recipes.Rows.Add(data.Name(id));var row=recipes.Rows[index];row.Tag=id;var cell=(DataGridViewComboBoxCell)row.Cells[1];cell.DisplayMember="Name";cell.ValueMember="Id";cell.DataSource=options;cell.Value=options.FirstOrDefault(r=>r.Id==settings.Choices.GetValueOrDefault(id))?.Id??options[0].Id;}initializing=false;
   tree.BeginUpdate();tree.Nodes.Clear();var byItem=plan.Stages.Where(s=>s.Recipe!=null).ToDictionary(s=>s.Item);TreeNode Build(string id,double amount,HashSet<string> path){var node=new TreeNode($"{data.Name(id)} · {N(amount)} {data.Unit(id)}");if(path.Contains(id)){node.Nodes.Add("↻ Rückführung – in der Gesamtbilanz berücksichtigt");return node;}if(byItem.TryGetValue(id,out var stage)){var next=new HashSet<string>(path){id};node.Nodes.Add($"{stage.Building.Name}: {stage.Count} × {N(stage.Clock)} % · Gesamtbedarf dieser Stufe: {N(stage.Rate)}/min");double runs=amount/stage.Recipe!.Outputs[0].Amount;foreach(var q in stage.Recipe.Inputs)node.Nodes.Add(Build(q.Item,q.Amount*runs,next));}else node.Nodes.Add(plan.Raw.ContainsKey(id)?"Rohstoff – Förderanlage siehe Maschinen":"Nebenprodukt-Rückführung oder externer Eingang – siehe Bilanz");return node;}
   tree.Nodes.Add(Build(settings.Target,settings.Rate,[]));tree.Nodes[0].Expand();foreach(TreeNode n in tree.Nodes[0].Nodes)n.Expand();tree.EndUpdate();
   status.Text=$"{plan.Raw.Count} Rohstoffe · {plan.Surplus.Count} Überschüsse · {plan.Shards} Leistungssplitter · Stromspitze: {N(plan.Peak)} MW · Baukosten ohne Transport und Stromnetz";
   Ui.Apply(this);
  }catch(Exception ex){initializing=false;plan=null;machineMap.Clear();summary.Text="Bitte passe deine Auswahl an";machineValue.Text=powerValue.Text=rawValue.Text=surplusValue.Text="—";if(overviewResizeHandler!=null){overview.Resize-=overviewResizeHandler;overviewResizeHandler=null;}foreach(Control c in overview.Controls.Cast<Control>().ToArray())c.Dispose();overview.Controls.Clear();var error=Theme.Label("Hier erscheint dein Bauplan.\n\n"+ex.Message,12);error.Dock=DockStyle.Top;error.Height=120;overview.Controls.Add(error);status.Text=ex.Message;stages.Rows.Clear();resources.Rows.Clear();surplus.Rows.Clear();costs.Rows.Clear();tree.Nodes.Clear();Ui.Apply(this);}
 }
 void Save(){try{Read();using var dialog=new SaveFileDialog{Filter=Ui.T("Produktionsplan (*.json)|*.json"),FileName="Produktionsplan.json"};if(dialog.ShowDialog()==DialogResult.OK)File.WriteAllText(dialog.FileName,JsonSerializer.Serialize(settings,new JsonSerializerOptions{WriteIndented=true}));}catch(Exception ex){MessageBox.Show(Ui.T(ex.Message));}}
 void LoadPlan(){using var dialog=new OpenFileDialog{Filter=Ui.T("Produktionsplan (*.json)|*.json")};if(dialog.ShowDialog()!=DialogResult.OK)return;try{var s=JsonSerializer.Deserialize<Settings>(File.ReadAllText(dialog.FileName))??throw new Exception("Ungültige Plandatei.");if(!data.Items.ContainsKey(s.Target)||s.Rate<.001||s.Rate>1e7||s.Clock<100||s.Clock>250||s.Miner<1||s.Miner>3||!new[]{.5,1d,2d}.Contains(s.Purity)||s.WellNodes<1||s.WellNodes>20)throw new Exception("Der Plan enthält ungültige Einstellungen.");s.OwnedMaterials??=[];s.MapPositions??=[];s.Choices??=[];initializing=true;settings=s;search.Text="";Filter();target.SelectedValue=s.Target;rate.Value=(decimal)s.Rate;overclock.Checked=s.Overclock;clock.Enabled=s.Overclock;clock.Value=(decimal)s.Clock;miner.SelectedIndex=s.Miner-1;purity.SelectedIndex=Array.IndexOf(new[]{.5,1d,2d},s.Purity);nodes.Value=s.WellNodes;initializing=false;Calculate();}catch(Exception ex){initializing=false;MessageBox.Show(Ui.T(ex.Message));}}
 void Export(){if(plan==null)return;using var dialog=new SaveFileDialog{Filter="CSV (*.csv)|*.csv",FileName="Produktionsplan.csv"};if(dialog.ShowDialog()!=DialogResult.OK)return;try{var b=new StringBuilder();void Row(params object[] cells)=>b.AppendLine(string.Join(";",cells.Select(x=>"\""+(Ui.T(x.ToString()??"")).Replace("\"","\"\"")+"\"")));Row("Ziel",data.Name(settings.Target),N(settings.Rate),data.Unit(settings.Target));foreach(var pair in new[]{("Maschinen",stages),("Rohstoffe",resources),("Überschüsse",surplus),("Baukosten",costs)}){Row("");Row(pair.Item1);Row(pair.Item2.Columns.Cast<DataGridViewColumn>().Select(c=>(object)c.HeaderText).ToArray());foreach(DataGridViewRow r in pair.Item2.Rows)Row(r.Cells.Cast<DataGridViewCell>().Select(c=>c.Value??"").ToArray());}Row("");foreach(var note in plan.Notes)Row(Ui.T(note));File.WriteAllText(dialog.FileName,b.ToString(),new UTF8Encoding(true));}catch(Exception ex){MessageBox.Show(Ui.T(ex.Message));}}
}
















